apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-poc
  template:
    metadata:
      labels:
        app: aks-poc
    spec:
      containers:
      - name: aks-poc
        image: wojtekacr.azurecr.io/aks-poc:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aks-poc-svc
spec:
  type: LoadBalancer
  selector:
    app: aks-poc
  ports:
  - port: 80
    targetPort: 80
