apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-poc
  template:
    metadata:
      labels:
        app: aks-poc
    spec:
      containers:
        - name: aks-poc
          image: wojtekacr.azurecr.io/aks-poc:v3
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: openai-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: aks-poc-svc
spec:
  type: LoadBalancer
  selector:
    app: aks-poc
  ports:
    - port: 80
      targetPort: 8080
